apiVersion: 1
# ðŸ“Œ Version format provisioning Grafana (stable depuis v8+)

contactPoints:
  - orgId: 1
    name: Discord CV Alerts
    receivers:
      - uid: discord-cv-webhook
        type: discord
        settings:
          url: https://discord.com/api/webhooks/1439965425814212651/Gkq7NGqFewz7qdxbzdhC5Zu8P-J3D8d4HlefJW-WjjLRGOh9Eh-XtyVqW3gnbpKZFUu8
          use_discord_username: true
        disableResolveMessage: false
