apiVersion: 1

policies:

  - orgId: 1

    receiver: Discord CV Alerts
    
    group_by: ['alertname', 'grafana_folder']
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h
    routes:
      - receiver: Discord CV Alerts
        
        object_matchers:
          - ['severity', '=', 'critical']
        group_wait: 5s
        
        repeat_interval: 5m
      - receiver: Discord CV Alerts
        object_matchers:
          - ['severity', '=', 'warning']
        
        group_wait: 10s
        repeat_interval: 30m
      - receiver: Discord CV Alerts
        object_matchers:
          - ['severity', '=', 'info']
        
        group_wait: 30s
        repeat_interval: 6h